language: ruby
before_script:
  - cp test/database.ci.yml test/database.yml
  - psql -c 'CREATE DATABASE ltree_hierarchy_test;' -U postgres
branches:
  only:
    - master
rvm:
  - 1.9.3
  - 2.0.0
  - rbx
  - jruby-19mode
gemfile:
  - test/gemfiles/Gemfile.rails-3.1.x
  - test/gemfiles/Gemfile.rails-3.2.x
  - test/gemfiles/Gemfile.rails-4.0.x
